version: '3.8'

services:
  sudoku-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sudoku-app
    ports:
      - "9090:8080"
    networks:
      - devops_net
    restart: unless-stopped

networks:
  devops_net:
    driver: bridge
