version: '3.8'

services:
  jenkins:
    image: ${JENKINS_IMAGE}
    container_name: ${JENKINS_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${JENKINS_PORT}:8080"
      - "${JENKINS_AGENT_PORT}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${NETWORK_NAME}

  sudoku-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sudoku-app
    ports:
      - "${SUDOKU_PORT}:8080"
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - jenkins

networks:
  ${NETWORK_NAME}:
    driver: bridge

volumes:
  jenkins_home:
